name: "Eywek's personal blog"
description: "Blogging about some tech stuff I've done"
meta_description: "Blogging about some tech stuff I've done"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "https://blog.eywek.fr"
# google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Valentin `Eywek`"

# Disqus config
# disqus-shortname: ""
