name: "Eywek's blog"
description: Blogging about tech and engineering stuffs
meta_description: "Blogging about tech and engineering stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /blog
domain_name: "https://eywek.github.io"
# google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Valentin `Eywek` Touffet"

# Disqus config
# disqus-shortname: ""
